
export const canon_name = {
    "Adak": "adak",
    "Adak - BETA": "adak",
    "Adak - Beta": "adak",
    "Asad Khal": "asad_khal",
    "Ascheberg": "ascheberg",
    "Assault on Grozny": "assault_on_grozny",
    "Assault on Mestia": "assault_on_mestia",
    "Bamyan": "bamyan",
    "Battle of Debrecen": "battle_of_debrecen",
    "Battle of Ia Drang": "battle_of_ia_drang",
    "Battle of Kerch": "battle_of_kerch",
    "Beirut": "beirut",
    "Belyaevo": "belyaevo",
    "Black Gold": "black_gold",
    "Brecourt Assault": "brecourt_assault",
    "Burning Sands": "burning_sands",
    "Carentan": "carentan",
    "Charlie's Point": "charlies_point",
    "Charlies Point": "charlies_point",
    "Dovre": "dovre",
    "Dovre Winter": "dovre_winter",
    "Dragon Fly": "dragon_fly",
    "Fallujah West": "fallujah_west",
    "Fallujah": "fallujah_west",
    "Fields of Kassel": "fields_of_kassel",
    "Fools Road": "fools_road",
    "Gaza": "gaza_2",
    "Goose Green": "goose_green",
    "Grostok": "grostok",
    "Hades Peak": "hades_peak",
    "Hill 488": "hill_488",
    "Iron Ridge": "iron_ridge",
    "Kafar Halab": "kafar_halab",
    "Kafr Halab": "kafar_halab",
    "Kashan Desert": "kashan_desert",
    "Kashan": "kashan_desert",
    "Khamisiyah": "khamisiyah",
    "Korbach": "korbach_offensive",
    "Korbach Offensive": "korbach_offensive",
    "Korbach Offensive - Beta": "korbach_offensive",
    "Korbach Offensive - BETA": "korbach_offensive",
    "Korengal": "korengal",
    "Kozelsk": "kozelsk",
    "Krivaja Valley": "krivaja_valley",
    "Kunar Province": "kunar_province",
    "Kunar Province - BETA": "kunar_province",
    "Kunar Province - Beta": "kunar_province",
    "Masirah": "masirah",
    "Merville": "merville",
    "Musa Qala - Beta": "musa_qala",
    "Musa Qala - BETA": "musa_qala",
    "Musa Qala": "musa_qala",
    "Muttrah City": "muttrah_city_2",
    "Nuijamaa": "nuijamaa",
    "Omaha Beach": "omaha_beach",
    "Op Barracuda": "op_barracuda",
    "Operation Barracuda": "op_barracuda",
    "Operation Bobcat": "operation_bobcat",
    "Operation Brunswick": "operation_brunswick",
    "Operation Falcon": "operation_falcon",
    "Operation Marlin": "operation_marlin",
    "Operation Soul Rebel": "operation_soul_rebel",
    "Operation Thunder": "operation_thunder",
    "Operation Thunder - BETA": "operation_thunder",
    "Operation Thunder - Beta": "operation_thunder",
    "Outpost": "outpost",
    "Pavlovsk Bay": "pavlovsk_bay",
    "Ramiel": "ramiel",
    "Ras el Masri": "ras_el_masri_2",
    "Ras El Masri": "ras_el_masri_2",
    "Reichswald": "reichswald",
    "Damascus": "road_to_damascus",
    "Road to Damascus": "road_to_damascus",
    "Road to Damascus - BETA": "road_to_damascus",
    "Road to Damascus - Beta": "road_to_damascus",
    "Route": "route",
    "Route E-106": "route",
    "Route E106": "route",
    "Route E 106": "route",
    "Rzhev": "rzhev",
    "Saaremaa": "saaremaa",
    "Sahel": "sahel",
    "Sbeneh Outskirts": "sbeneh_outskirts",
    "Sbeneh": "sbeneh_outskirts",
    "Shahadah": "shahadah",
    "Shijia": "shijiavalley",
    "Shijia Valley": "shijiavalley",
    "Shijiavalley": "shijiavalley",
    "Silent Eagle": "silent_eagle",
    "Stalingrad": "stalingrad",
    "Stalingrad Winter": "stalingrad",
    "Stalingrad Summer": "stalingrad_summer",
    "Tad Sae": "tad_sae",
    "Tad Sae Offensive": "tad_sae",
    "The Falklands": "the_falklands",
    "Falklands": "the_falklands",
    "Ulyanovsk": "ulyanovsk",
    "Vadso City": "vadso_city",
    "Vung Ro": "vung_ro",
    "Wanda Shan": "wanda_shan",
    "Xiangshan": "xiangshan",
    "Yamalia": "yamalia",
    "Zakho": "zakho",
    "Zakho - BETA": "zakho",
    "Zakho - Beta": "zakho",
    "Albasrah": "albasrah_2",
    "Al Basrah": "albasrah_2",
    "Karbala": "karbala",
    "Kokan": "kokan",
    "Lashkar Valley": "lashkar_valley",
    "Shipment": "shipment",
    "Deagle5": "deagle5",
    "Medelivka": "medelivka",
    "Medelivka Seasonal": "medelivka"

}

export const canon_layout = {
  '16': 'Inf',
  '32': 'Std',
  '64': 'Alt',
  '128': 'Lrg'
}